CREATE TABLE "subjects" (
  "pk_name" varchar PRIMARY KEY
);

CREATE TABLE "subjects_mentioned_in_algorithm" (
  "pk_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_subject" varchar NOT NULL,
  "fk_algorithm" varchar NOT NULL,
  "factor" real NOT NULL CONSTRAINT positive_subject_factor CHECK (factor >= 0)
);

CREATE TABLE "major_algorithms" (
  "pk_name" varchar PRIMARY KEY
);

CREATE TABLE "thresholds" (
  "pk_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_major" int NOT NULL,
  "recrutation_year" int NOT NULL,
  "round_1" real NOT NULL,
  "round_2" real,
  "round_3" real,
	CONSTRAINT unique_major_per_year UNIQUE(fk_major,recrutation_year)
);


CREATE TABLE "recruitment_exemption_documents" (
  "pk_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_type" varchar NOT NULL,
  "fk_candidate" int NOT NULL
);

CREATE TABLE "recruitment_exemption_document_types" (
  "pk_name" varchar PRIMARY KEY
);

CREATE TABLE "departments" (
  "pk_number" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL UNIQUE,
  "description" text
);

CREATE TABLE "majors" (
  "pk_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL UNIQUE,
  "description" text,
  "number_of_places" integer CONSTRAINT positive_number_of_places CHECK (number_of_places > 0),
  "fk_department" integer NOT NULL,
  "fk_algorithm" varchar NOT NULL
);

CREATE TABLE "courses" (
  "pk_code" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text,
  "fk_major" integer NOT NULL
);

CREATE TABLE "recruitment_workers" (
  "pk_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "surname" varchar NOT NULL,
  "phone_number" varchar,
  "mail" varchar,
  "fk_account" varchar NOT NULL
);

CREATE TABLE "recruitment_workers_majors"(
	"pk_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"fk_recruitment_worker" INTEGER NOT NULL,
	"fk_major" INTEGER NOT NULL
);

CREATE TABLE "accounts" (
  "pk_login" varchar PRIMARY KEY,
  "password" varchar NOT NULL
);

CREATE TYPE round AS ENUM ('FIRST', 'SECOND', 'THIRD');

CREATE TABLE "recruitment_applications" (
  "pk_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_major" integer NOT NULL,
  "fk_candidate" integer NOT NULL,
  "year" integer NOT NULL,
  "round" round NOT NULL
);

CREATE TABLE "documents_exempting_from_fees" (
  "pk_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_type" varchar NOT NULL,
  "fk_candidate" integer NOT NULL,
  "date_of_issue" date NOT NULL,
  "document_id" varchar NOT NULL
);

CREATE TABLE "document_exempting_from_fees_types" (
  "pk_name" varchar PRIMARY KEY
);

CREATE TABLE "candidates" (
  "pk_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_account" varchar NOT NULL,
  "name" varchar NOT NULL,
  "surname" varchar NOT NULL,
  "id_document_number" varchar NOT NULL,
  "fk_id_document_type" varchar NOT NULL,
  "fk_nationality" varchar NOT NULL,
  "pesel" varchar(11)
);

CREATE TABLE "id_document_types" (
  "pk_name" varchar PRIMARY KEY
);

CREATE TABLE "exams" (
  "pk_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" varchar NOT NULL,
  "fk_candidate" integer NOT NULL,
  "date" date NOT NULL, 
  "fk_exam_type" varchar NOT NULL
);

CREATE TABLE "exam_types" (
  "pk_name" varchar PRIMARY KEY,
  "minimum_points_score" real NOT NULL CONSTRAINT positive_points CHECK (minimum_points_score >= 0),
  "maximum_points_score" real NOT NULL,
  "multiplier" real NOT NULL CONSTRAINT positive_multiplier CHECK (multiplier >= 0),
	CONSTRAINT min_less_than_max CHECK (minimum_points_score < maximum_points_score)
);

CREATE TABLE "first_degree_diplomas" (
  "pk_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "university_name" varchar NOT NULL,
  "average_mark" real NOT NULL CONSTRAINT positive_avg_mark CHECK (average_mark >= 0),
  "fk_candidate" integer NOT NULL,
  "thesis_mark" real NOT NULL CONSTRAINT positive_thesis_mark CHECK (thesis_mark >= 0)
);

CREATE TABLE "subject_results" (
  "pk_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fk_subject" varchar NOT NULL,
  "fk_exam" integer NOT NULL,
  "points" real NOT NULL CONSTRAINT positive_points CHECK (points >= 0)
);

CREATE TABLE "nationalities" (
  "pk_name" varchar PRIMARY KEY,
  "studies_fee_free" bool NOT NULL
);

ALTER TABLE "recruitment_applications" ADD FOREIGN KEY ("fk_candidate") REFERENCES "candidates" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "recruitment_workers" ADD FOREIGN KEY ("fk_account") REFERENCES "accounts" ("pk_login") ON DELETE CASCADE;

ALTER TABLE "documents_exempting_from_fees" ADD FOREIGN KEY ("fk_candidate") REFERENCES "candidates" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "exams" ADD FOREIGN KEY ("fk_candidate") REFERENCES "candidates" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "subjects_mentioned_in_algorithm" ADD FOREIGN KEY ("fk_subject") REFERENCES "subjects" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "subjects_mentioned_in_algorithm" ADD FOREIGN KEY ("fk_algorithm") REFERENCES "major_algorithms" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "majors" ADD FOREIGN KEY ("fk_algorithm") REFERENCES "major_algorithms" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "recruitment_exemption_documents" ADD FOREIGN KEY ("fk_type") REFERENCES "recruitment_exemption_document_types" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "majors" ADD FOREIGN KEY ("fk_department") REFERENCES "departments" ("pk_number") ON DELETE RESTRICT;

ALTER TABLE "courses" ADD FOREIGN KEY ("fk_major") REFERENCES "majors" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "recruitment_workers_majors" ADD FOREIGN KEY ("fk_recruitment_worker") REFERENCES "recruitment_workers" ("pk_id") ON DELETE CASCADE;
ALTER TABLE "recruitment_workers_majors" ADD FOREIGN KEY ("fk_major") REFERENCES "majors" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "recruitment_applications" ADD FOREIGN KEY ("fk_major") REFERENCES "majors" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "thresholds" ADD FOREIGN KEY ("fk_major") REFERENCES "majors" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "subject_results" ADD FOREIGN KEY ("fk_exam") REFERENCES "exams" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "exams" ADD FOREIGN KEY ("fk_exam_type") REFERENCES "exam_types" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "first_degree_diplomas" ADD FOREIGN KEY ("fk_candidate") REFERENCES "candidates" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "candidates" ADD FOREIGN KEY ("fk_id_document_type") REFERENCES "id_document_types" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "candidates" ADD FOREIGN KEY ("fk_nationality") REFERENCES "nationalities" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "documents_exempting_from_fees" ADD FOREIGN KEY ("fk_type") REFERENCES "document_exempting_from_fees_types" ("pk_name") ON DELETE RESTRICT;

ALTER TABLE "candidates" ADD FOREIGN KEY ("fk_account") REFERENCES "accounts" ("pk_login") ON DELETE CASCADE;

ALTER TABLE "recruitment_exemption_documents" ADD FOREIGN KEY ("fk_candidate") REFERENCES "candidates" ("pk_id") ON DELETE CASCADE;

ALTER TABLE "subject_results" ADD FOREIGN KEY ("fk_subject") REFERENCES "subjects" ("pk_name") ON DELETE RESTRICT;
